export const GalleryItems = [
    {
        id: 1,
        category: "wisata_alam",
        titleId: "Gunung Bromo",
        titleEn: "Mount Bromo",
        locationId: "Jawa Timur",
        locationEn: "East Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782776/Gunung_Bromo_Provinsi_Jawa_Timur_ft9wwk.jpg",
        size: "large",
    },
    {
        id: 2,
        category: "kuliner",
        titleId: "Rendang",
        titleEn: "Rendang",
        locationId: "Sumatera Barat",
        locationEn: "West Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Rendang-Sumatra_Barat_cpligi.jpg",
        size: "small",
    },
    {
        id: 3,
        category: "bangunan_bersejarah",
        titleId: "Candi Borobudur",
        titleEn: "Borobudur Temple",
        locationId: "Jawa Tengah",
        locationEn: "Central Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780151/Candi_Borobudur-Jawa_Tengah_x1mgir.jpg",
        size: "medium",
    },
    {
        id: 4,
        category: "budaya",
        titleId: "Tari Saman",
        titleEn: "Saman Dance",
        locationId: "Aceh",
        locationEn: "Aceh",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Tari_Saman-Provinsi_Aceh_o3ed0x.jpg",
        size: "small",
    },
    {
        id: 5,
        category: "wisata_alam",
        titleId: "Raja Ampat",
        titleEn: "Raja Ampat",
        locationId: "Papua Barat Daya",
        locationEn: "Southwest Papua",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782775/Raja_Ampat_Provinsi_Papua_Barat_Daya_d7bkij.jpg",
        size: "small",
    },
    {
        id: 6,
        category: "kuliner",
        titleId: "Pempek",
        titleEn: "Pempek",
        locationId: "Sumatera Selatan",
        locationEn: "South Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Pempek-Sumatra_Selatan_bi6hzf.jpg",
        size: "medium",
    },
    {
        id: 7,
        category: "bangunan_bersejarah",
        titleId: "Monumen Nasional",
        titleEn: "National Monument",
        locationId: "Jakarta",
        locationEn: "Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780151/Monumen_Nasional-Jakarta_r9ppox.jpg",
        size: "large",
    },
    {
        id: 8,
        category: "budaya",
        titleId: "Wayang Kulit",
        titleEn: "Shadow Puppet",
        locationId: "Jawa Tengah",
        locationEn: "Central Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781815/Wayang_Kulit_Provinsi_Jawa_Tengah_d0o5y3.jpg",
        size: "small",
    },
    {
        id: 9,
        category: "wisata_alam",
        titleId: "Danau Toba",
        titleEn: "Lake Toba",
        locationId: "Sumatera Utara",
        locationEn: "North Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782775/Danau_Toba_Provinsi_Sumatra_Utara_moffvx.jpg",
        size: "small",
    },
    {
        id: 10,
        category: "kuliner",
        titleId: "Gudeg",
        titleEn: "Gudeg",
        locationId: "Yogyakarta",
        locationEn: "Yogyakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Gudeg-Yogyakarta_i3bn27.jpg",
        size: "medium",
    },
    {
        id: 11,
        category: "bangunan_bersejarah",
        titleId: "Rumah Gadang",
        titleEn: "Gadang House",
        locationId: "Sumatera Barat",
        locationEn: "West Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780861/Rumah_Gadang-Sumatra_Barat_binmwn.jpg",
        size: "large",
    },
    {
        id: 12,
        category: "budaya",
        titleId: "Batik",
        titleEn: "Batik",
        locationId: "Yogyakarta",
        locationEn: "Yogyakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781820/Batik-Yogyakarta_walcsx.jpg",
        size: "small",
    },
    {
        id: 13,
        category: "wisata_alam",
        titleId: "Pantai Pink",
        titleEn: "Pink Beach",
        locationId: "Nusa Tenggara Barat",
        locationEn: "West Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782773/Pantai_Pink_Provinsi_Nusa_Tenggara_Barat_NTB_z378ur.jpg",
        size: "small",
    },
    {
        id: 14,
        category: "kuliner",
        titleId: "Soto Banjar",
        titleEn: "Soto Banjar",
        locationId: "Kalimantan Selatan",
        locationEn: "South Kalimantan",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Soto_Banjar-Kalimantan_Selatan_t5m95r.jpg",
        size: "medium",
    },
    {
        id: 15,
        category: "bangunan_bersejarah",
        titleId: "Candi Prambanan",
        titleEn: "Prambanan Temple",
        locationId: "Yogyakarta",
        locationEn: "Yogyakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780151/Candi_Prambanan-Yogyakarta_r9d6al.jpg",
        size: "large",
    },
    {
        id: 16,
        category: "budaya",
        titleId: "Tari Kecak",
        titleEn: "Kecak Dance",
        locationId: "Bali",
        locationEn: "Bali",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Tari_Kecak_Provinsi_Bali_pocxhw.jpg",
        size: "small",
    },
    {
        id: 17,
        category: "wisata_alam",
        titleId: "Kawah Ijen",
        titleEn: "Ijen Crater",
        locationId: "Jawa Timur",
        locationEn: "East Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782774/Kawah_Ijen_Provinsi_Jawa_Timur_knc4iq.jpg",
        size: "small",
    },
    {
        id: 18,
        category: "kuliner",
        titleId: "Rawon",
        titleEn: "Rawon",
        locationId: "Jawa Timur",
        locationEn: "East Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Rawon-Jawa_Timur_slkla4.jpg",
        size: "medium",
    },
    {
        id: 19,
        category: "bangunan_bersejarah",
        titleId: "Rumah Tongkonan",
        titleEn: "Tongkonan House",
        locationId: "Sulawesi Selatan",
        locationEn: "South Sulawesi",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780861/Rumah_Tongkonan-Sulawesi_Selatan_rlhdee.jpg",
        size: "large",
    },
    {
        id: 20,
        category: "budaya",
        titleId: "Reog Ponorogo",
        titleEn: "Reog Ponorogo",
        locationId: "Jawa Timur",
        locationEn: "East Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781818/Reog_Ponorogo_Provinsi_Jawa_Timur_wwpq4y.jpg",
        size: "small",
    },
    {
        id: 21,
        category: "wisata_alam",
        titleId: "Taman Nasional Komodo",
        titleEn: "Komodo National Park",
        locationId: "Nusa Tenggara Timur",
        locationEn: "East Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782774/Taman_Nasional_Komodo_Provinsi_Nusa_Tenggara_Timur_NTT_ueujnm.jpg",
        size: "small",
    },
    {
        id: 22,
        category: "kuliner",
        titleId: "Kerak Telor",
        titleEn: "Kerak Telor",
        locationId: "DKI Jakarta",
        locationEn: "DKI Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Kerak_Telor-DKI_Jakarta_lh5k6m.jpg",
        size: "medium",
    },
    {
        id: 23,
        category: "bangunan_bersejarah",
        titleId: "Lawang Sewu",
        titleEn: "Lawang Sewu",
        locationId: "Semarang",
        locationEn: "Semarang",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780151/Lawang_Sewu-Semarang_xlt3rj.jpg",
        size: "large",
    },
    {
        id: 24,
        category: "budaya",
        titleId: "Tenun Ikat",
        titleEn: "Ikat Weaving",
        locationId: "Nusa Tenggara Timur",
        locationEn: "East Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Tenun_Ikat_Provinsi_Nusa_Tenggara_Timur_NTT_e68rfb.jpg",
        size: "small",
    },
    {
        id: 25,
        category: "wisata_alam",
        titleId: "Gunung Rinjani",
        titleEn: "Mount Rinjani",
        locationId: "Nusa Tenggara Barat",
        locationEn: "West Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782773/Gunung_Rinjani_Provinsi_Nusa_Tenggara_Barat_NTB_bh1udq.jpg",
        size: "small",
    },
    {
        id: 26,
        category: "kuliner",
        titleId: "Mie Aceh",
        titleEn: "Aceh Noodles",
        locationId: "Aceh",
        locationEn: "Aceh",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Mie_Aceh-Aceh_ekluu4.jpg",
        size: "medium",
    },
    {
        id: 27,
        category: "bangunan_bersejarah",
        titleId: "Gedung Sate",
        titleEn: "Gedung Sate",
        locationId: "Bandung",
        locationEn: "Bandung",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780150/Gedung_Sate-Bandung_m8a89g.jpg",
        size: "large",
    },
    {
        id: 28,
        category: "budaya",
        titleId: "Upacara Ngaben",
        titleEn: "Ngaben Ceremony",
        locationId: "Bali",
        locationEn: "Bali",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781820/Upacara_Ngaben_Provinsi_Bali_j23ikm.jpg",
        size: "small",
    },
    {
        id: 29,
        category: "wisata_alam",
        titleId: "Pantai Kuta",
        titleEn: "Kuta Beach",
        locationId: "Bali",
        locationEn: "Bali",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782774/Pantai_Kuta_Provinsi_Bali_jnu99d.jpg",
        size: "small",
    },
    {
        id: 30,
        category: "kuliner",
        titleId: "Ayam Betutu",
        titleEn: "Ayam Betutu",
        locationId: "Bali",
        locationEn: "Bali",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777219/Ayam_Betutu-Bali_tm8izv.jpg",
        size: "medium",
    },
    {
        id: 31,
        category: "bangunan_bersejarah",
        titleId: "Fort Rotterdam",
        titleEn: "Fort Rotterdam",
        locationId: "Makassar",
        locationEn: "Makassar",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780151/Fort_Rotterdam-Makassar_or8rf8.jpg",
        size: "large",
    },
    {
        id: 32,
        category: "budaya",
        titleId: "Keris",
        titleEn: "Keris",
        locationId: "Jawa Tengah",
        locationEn: "Central Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Keris_Provinsi_Jawa_Tengah_czxfrt.jpg",
        size: "small",
    },
    {
        id: 33,
        category: "wisata_alam",
        titleId: "Danau Kelimutu",
        titleEn: "Kelimutu Lake",
        locationId: "Nusa Tenggara Timur",
        locationEn: "East Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782773/Danau_Kelimutu_Provinsi_Nusa_Tenggara_Timur_NTT_aowij8.jpg",
        size: "small",
    },
    {
        id: 34,
        category: "kuliner",
        titleId: "Coto Makassar",
        titleEn: "Coto Makassar",
        locationId: "Sulawesi Selatan",
        locationEn: "South Sulawesi",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777219/Coto_Makassar-Sulawesi_Selatan_ssvcks.jpg",
        size: "medium",
    },
    {
        id: 35,
        category: "bangunan_bersejarah",
        titleId: "Kota Tua",
        titleEn: "Old Town",
        locationId: "Jakarta",
        locationEn: "Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780150/Kota_Tua-Jakarta_p4uoit.jpg",
        size: "large",
    },
    {
        id: 36,
        category: "budaya",
        titleId: "Tari Jaipong",
        titleEn: "Jaipong Dance",
        locationId: "Jawa Barat",
        locationEn: "West Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Tari_Jaipong_Provinsi_Jawa_Barat_bfsmrj.jpg",
        size: "small",
    },
    {
        id: 37,
        category: "wisata_alam",
        titleId: "Taman Laut Bunaken",
        titleEn: "Bunaken Marine Park",
        locationId: "Sulawesi Utara",
        locationEn: "North Sulawesi",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782772/Taman_Laut_Bunaken_Provinsi_Sulawesi_Utara_gclqbm.jpg",
        size: "small",
    },
    {
        id: 38,
        category: "kuliner",
        titleId: "Bika Ambon",
        titleEn: "Bika Ambon",
        locationId: "Sumatera Utara",
        locationEn: "North Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777219/Bika_Ambon-Sumatra_Utara_skjcsj.jpg",
        size: "medium",
    },
    {
        id: 39,
        category: "bangunan_bersejarah",
        titleId: "Rumah Honai",
        titleEn: "Honai House",
        locationId: "Papua",
        locationEn: "Papua",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780862/Rumah_Honai-Papua_tu8an1.jpg",
        size: "large",
    },
    {
        id: 40,
        category: "budaya",
        titleId: "Rencong",
        titleEn: "Rencong",
        locationId: "Aceh",
        locationEn: "Aceh",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781818/Rencong_Provinsi_Aceh_bbqpgr.jpg",
        size: "small",
    },
    {
        id: 41,
        category: "wisata_alam",
        titleId: "Air Terjun Tumpak Sewu",
        titleEn: "Tumpak Sewu Waterfall",
        locationId: "Jawa Timur",
        locationEn: "East Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782772/Air_Terjun_Tumpak_Sewu_Provinsi_Jawa_Timur_ipm0sv.jpg",
        size: "small",
    },
    {
        id: 42,
        category: "kuliner",
        titleId: "Pendap Bengkulu",
        titleEn: "Pendap Bengkulu",
        locationId: "Bengkulu",
        locationEn: "Bengkulu",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Pendap-Bengkulu_mxhkdk.jpg",
        size: "medium",
    },
    {
        id: 43,
        category: "bangunan_bersejarah",
        titleId: "Taman Mini Indonesia Indah",
        titleEn: "Beautiful Indonesia Miniature Park",
        locationId: "Jakarta",
        locationEn: "Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780152/Taman_Mini_Indonesia_Indah-Jakarta_vnpjzn.jpg",
        size: "large",
    },
    {
        id: 44,
        category: "budaya",
        titleId: "Tari Piring",
        titleEn: "Plate Dance",
        locationId: "Sumatera Barat",
        locationEn: "West Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781816/Tari_Piring_Provinsi_Sumatra_Barat_mw1ipw.jpg",
        size: "small",
    },
    {
        id: 45,
        category: "wisata_alam",
        titleId: "Pulau Derawan",
        titleEn: "Derawan Island",
        locationId: "Kalimantan Timur",
        locationEn: "East Kalimantan",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782773/Pulau_Derawan_Provinsi_Kalimantan_Timur_l6a3li.jpg",
        size: "small",
    },
    {
        id: 46,
        category: "kuliner",
        titleId: "Garang Asem",
        titleEn: "Garang Asem",
        locationId: "Jawa Tengah",
        locationEn: "Central Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Garang_Asem-Jawa_Tengah_zjnvwr.jpg",
        size: "medium",
    },
    {
        id: 47,
        category: "bangunan_bersejarah",
        titleId: "Jam Gadang",
        titleEn: "Jam Gadang",
        locationId: "Sumatera Barat",
        locationEn: "West Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780499/Jam_Gadang-Sumatra_Barat_f28gc6.jpg",
        size: "large",
    },
    {
        id: 48,
        category: "budaya",
        titleId: "Badik",
        titleEn: "Badik",
        locationId: "Sulawesi Selatan",
        locationEn: "South Sulawesi",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Badik_Provinsi_Sulawesi_Selatan_gsvejw.jpg",
        size: "small",
    },
    {
        id: 49,
        category: "wisata_alam",
        titleId: "Ngarai Sianok",
        titleEn: "Sianok Canyon",
        locationId: "Sumatera Barat",
        locationEn: "West Sumatra",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782772/Ngarai_Sianok_Provinsi_Sumatra_Barat_g3c8rp.jpg",
        size: "small",
    },
    {
        id: 50,
        category: "kuliner",
        titleId: "Seruit",
        titleEn: "Seruit",
        locationId: "Lampung",
        locationEn: "Lampung",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Seruit-Lampung_frwdrn.jpg",
        size: "medium",
    },
    {
        id: 51,
        category: "bangunan_bersejarah",
        titleId: "Gedung Merdeka",
        titleEn: "Merdeka Building",
        locationId: "Bandung",
        locationEn: "Bandung",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780150/Gedung_Merdeka-Bandung_v07wje.jpg",
        size: "large",
    },
    {
        id: 52,
        category: "budaya",
        titleId: "Upacara Rambu Solo",
        titleEn: "Rambu Solo Ceremony",
        locationId: "Sulawesi Selatan (Toraja)",
        locationEn: "South Sulawesi (Toraja)",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781817/Upacara_Rambu_Solo_Provinsi_Sulawesi_Selatan_Toraja_bue5xf.jpg",
        size: "small",
    },
    {
        id: 53,
        category: "wisata_alam",
        titleId: "Bukit Teletubbies",
        titleEn: "Teletubbies Hill",
        locationId: "Jawa Timur (Bromo)",
        locationEn: "East Java (Bromo)",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782775/Bukit_Teletubbies_Provinsi_Jawa_Timur_Bromo_kmwno0.jpg",
        size: "small",
    },
    {
        id: 54,
        category: "kuliner",
        titleId: "Karedok",
        titleEn: "Karedok",
        locationId: "Jawa Barat",
        locationEn: "West Java",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777220/Karedok-Jawa_Barat_s4fu31.jpg",
        size: "medium",
    },
    {
        id: 55,
        category: "bangunan_bersejarah",
        titleId: "Istana Merdeka",
        titleEn: "Merdeka Palace",
        locationId: "Jakarta",
        locationEn: "Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780150/Istana_Merdeka-Jakarta_a3ax34.jpg",
        size: "large",
    },
    {
        id: 56,
        category: "budaya",
        titleId: "Mandau",
        titleEn: "Mandau",
        locationId: "Kalimantan Barat",
        locationEn: "West Kalimantan",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767781816/Mandau_Provinsi_Kalimantan_Barat_pp68uc.jpg",
        size: "small",
    },
    {
        id: 57,
        category: "wisata_alam",
        titleId: "Taman Nasional Ujung Kulon",
        titleEn: "Ujung Kulon National Park",
        locationId: "Banten",
        locationEn: "Banten",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767782773/Taman_Nasional_Ujung_Kulon_Provinsi_Banten_hrirnd.jpg",
        size: "small",
    },
    {
        id: 58,
        category: "kuliner",
        titleId: "Ikan Bakar Manokwari",
        titleEn: "Ikan Bakar Manokwari",
        locationId: "Papua",
        locationEn: "Papua",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Ikan_Bakar_Manokwari-Papua_b93qjb.jpg",
        size: "medium",
    },
    {
        id: 59,
        category: "bangunan_bersejarah",
        titleId: "Rumah Joglo",
        titleEn: "Joglo House",
        locationId: "Yogyakarta",
        locationEn: "Yogyakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780861/Rumah_Joglo-Yogyakarta_ayz38a.jpg",
        size: "large",
    },
    {
        id: 60,
        category: "kuliner",
        titleId: "Gulai Belacan",
        titleEn: "Gulai Belacan",
        locationId: "Riau",
        locationEn: "Riau",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Gulai_Belacan-Riau_ft2chc.jpg",
        size: "small",
    },
    {
        id: 61,
        category: "bangunan_bersejarah",
        titleId: "Gedung Kesenian",
        titleEn: "Arts Building",
        locationId: "Jakarta",
        locationEn: "Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780149/Gedung_Kesenian-Jakarta_pbw27d.jpg",
        size: "small",
    },
    {
        id: 62,
        category: "kuliner",
        titleId: "Bau Peapi",
        titleEn: "Bau Peapi",
        locationId: "Sulawesi Barat",
        locationEn: "West Sulawesi",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777218/Bau_Peapi-Sulawesi_Barat_hsdpqt.jpg",
        size: "medium",
    },
    {
        id: 63,
        category: "bangunan_bersejarah",
        titleId: "Monumen Pancasila Sakti",
        titleEn: "Sacred Pancasila Monument",
        locationId: "DKI Jakarta",
        locationEn: "DKI Jakarta",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767780109/Monumen_Pancasila_Sakti-DKI_Jakarta_jycrly.jpg",
        size: "large",
    },
    {
        id: 64,
        category: "kuliner",
        titleId: "Ayam Bakar",
        titleEn: "Grilled Chicken",
        locationId: "Nusa Tenggara Barat",
        locationEn: "West Nusa Tenggara",
        image: "https://res.cloudinary.com/dmx8hcmxh/image/upload/v1767777219/Ayam_bakar-Nusa_Tenggara_Barat_hcltjz.jpg",
        size: "small",
    },
];
